### ISSUE TITLE
ALU writes to multiple things at a time.

### ISSUE THREAD

**Issue by yaqiz01** [raghup17/plasticine#2]
In pir/spatial there are cases when alu outputs are connected to multiple outputs, for example accumulation write to network and accum at same time. There’s also case when 1 addr is used at multiple srams. Is there a way in pisa that I can specify multiple output for the alu. Like result becomes a list?

**Comment by raghup17** [comment]
The current convention is that the output of the ALU goes to a register. If there are other places (e.g. write addr, read addr) it goes to, such configurations are specified at the place where it is used. For instance, if the output of ALU is to be written to register as well as used as read address for two scratchpads, the config would be something like:

```
// For scratchpads, say s0 and s1:
{ "ra" : "s2", "wa" : "x", "wd" : "x" },
{ "ra" : "s2", "wa" : "x", "wd" : "x" }

// For pipeStage P2, say
 {
  "opA" : ..
  "opB" : .. 
  "opcode" : ..
  "result" : "r0"
}
```

It happens to be this way because of the way I parse the JSON; I can look at specific sub-maps and parse the configs for specific regions of a CU. But it doesn't have to be this way I guess. Let me know if this makes sense and would work for you.

**Comment by blackwings-01** [comment]
There's also chance you would write to two registers at a time. For accumulation, the alu is writing both the accumulator register and the register that connects to scalarOut/vecout depends on whether it's reg accum or block reduce

**Comment by raghup17** [comment]
I thought that the accumulator register,  scalarOut register, and the register connected to the local scratchpad write ports is the exact same register. Also, for blockreduce, why do we need the scalar reduction tree?

**Comment by blackwings-01** [comment]
I guess if they are exactly same it would be fine. In PIR the are different registers before coloring, which might appears to be interfering if they have the same color. I have to add a handle on that. For block reduce it will write to local sram register and vecout register at the same time. It's not sure which sram placer will pick for local accumulation. So it's not guaranteed vecout and local accum will have the same register.

**Comment by raghup17** [comment]
For scalar accumulations, we could do this temporarily: Since you have an empty stage after accumulations, you could use that to move the accumulator value to the right place. This way, you need not modify the register allocator.

For Block reduces: The current assumption is that there is only one source for local write data, which is the special "write data" register. In other words, "local write data" register is connected to the write ports of all scratchpads. This would give the placer the freedom to place the accumulator RAM anywhere. Are you suggesting that we could potentially write different local values to different local scratchpads using the same write address?

**Comment by raghup17** [comment]
Closing issue.
