### ISSUE TITLE
Pisa Codegen Questions

### ISSUE THREAD

**Issue by yaqiz01** [raghup17/plasticine#6]
![blank](https://cloud.githubusercontent.com/assets/5553709/19755477/15d30c70-9bcb-11e6-8c2e-8a543324c9d1.png)
1. For a lut like above, if input 0, and 2 are connected while 1 and 3 are don't care, when generating the lookup table, will the input be `1010` or `0101`? At the moment the former is been used, but I can also change to the later

**Comment by raghup17** [comment]
Ah. Looks like I wrote a comment that answers this exact question:
  // NOTE: io.ins is a scala collection where MSB is in position 0                                                                                                                                                  
  // Users of LUTs must ensure that MSB of inputs must be in position 0

This means that the input will be 1010. Sorry, I should've brought this up before.

**Comment by blackwings-01** [comment]
Nice, surprisingly we were making the same assumption. 
2. Do you want to use "x" for unused stages, counters like we do for cu and tables, just to make the json shorter and potentially easier for you to write one? I don't have any preference on this one

**Comment by raghup17** [comment]
Yeah, I like that idea. So we are currently having 'x's to denote unused LUTs, Crossbars, CUs, Pipe Stages, and Counters. Might as well use 'x' to denote unused scratchpads too.

**Comment by blackwings-01** [comment]
Do you expect accumInit when the stage is not a accumulation stage?

**Comment by blackwings-01** [comment]
If a Pipeline has a CounterChain ( ctr1, ctr2, ctr3), then the doneDelay is added to ctr3 or ctr1? I assume ctr1?
@raghup17

**Comment by raghup17** [comment]
1. No, but it doesn't hurt if you add it anyway.
2. Delay is to the outermost counter, as you said.
3. Better if start and end values of FIFO are coming from scalarIn. A few small issues here: 
       a. We have 4 scratchpads, but only two scalarIn registers in the empty stage. We may have to increase scalarIn registers to 4 (or 8, including both start and end?) if we want to support 4 independent FIFOs. Increasing it to 8 would be hard; 
       b. Are we hard-coding registers to correspond to FIFOs? Depending on this, I will have to add a Mux (and you don't have to specify "e<foo>", just "e"), or not. Either works, just wanted to confirm.
4. I was planning on setting a "fifoMode" for both the reading and writing side. <to be continued>

**Comment by blackwings-01** [comment]
5. For `deqEn ` it can be the same since it's generated locally. For `enqEn` though it's a tokenIn since it's generated by the remote writer. In double buffer case, we have the local version of the counter that does the remote address calculation, so that's from the local EnableLUT, which would be different. I guess the correspondence is that `swapRead` is `deqEn` and `swapWrite` is `enqEn`? I can generate them as these name if it's more convenient.

**Comment by raghup17** [comment]
3. Not sure I completely follow: Are you saying that it will always be a known constant? I'm guessing not. In our current setup, since we only have two scalarIn registers, we will be able to support one FIFO (one scalarIn for start, one for end). We could use reg12 for FIFO start, reg13 for FIFO end. I've added a comment next to the scalarIn registers about this.
About supporting less than 4 FIFOs: Each scratchpad can be independently configured to operate as a FIFO or not. The issue will be that we don't have enough scalarIns to make them all dynamically sized. This shouldn't be a problem if the sizes are known at compile time.

4. Great!

5. Yeah, the correspondence is with swapRead <-> deqEn, and swapWrite <-> enqEn. It would be nice if you can use the same name. Maybe we can stick to enqEn and deqEn, since they are a bit more general.

**Comment by blackwings-01** [comment]
1. Currently the way to specify swap read and swap write are through specifying the corresponding counter index. But if it's tile load, the swap write of the FIFO inside the next CU should be MC.done, which is a counter that I don't have access to. It seems we need to be able to route this signal to the receiver and a way of express this in pisa
