### ISSUE TITLE
Register mapping

### ISSUE THREAD

**Issue by yaqiz01** [raghup17/plasticine#7]
Currently both Vector Output Register and Write Address Register are mapped to register 0. However, in case of block reduce, both register are alive in the last stage. Consider overlapping sram load register with vector output/write port/write address register? They usually don't overlap in live range

Just to confirm we are not buffering vector input in empty stage during remote write to sram or FIFO write right?

**Comment by raghup17** [comment]
1. Just so I understand: reg 0 contains local write addr, reg 1 contains local write data. Reg 0 is also the vector output register i.e., the data that gets sent out of the CU. In case of BlockReduce, we will use both reg 0 (addr) and reg 1 (accumulated data) to locally update the accumulator. The issue is because we will need to also write this data remotely, but reg 0 is occupied with something else. Is this right?Why not use the register used for data (reg 1 ,currently)? Just a thought; we can use whichever register you think is convenient.

2. Yeah, we are not buffering data for remote writes, remote data is written to scratchpad / FIFO directly.

**Comment by blackwings-01** [comment]
1. there's no good reason for local write port register and vector out register cannot be together in hardware excepts it's a compiler limitation at the moment. Both registers when used appears to be a live out of the last stage, and I don't have enough information to distinguish whether they are the same variable or not because there's no concept of BlockReduce in PIR. I can't distinguish whether the user wants to locally accumulate and remote write or there's a local write and a separate variable going out as a vector output, though we don't support that in spatial, it would be a legal PIR. 
If you don't mind, can we use register 8 and 9 for write addr and local write port register? It's usually pretty safe to overlap "read type" register such as scalarIn, load register and "write type" register such as write addr/port/vector output register since write usually happens at the very end. And we might be able to save some registers by doing this.

**Comment by raghup17** [comment]
Sure, fine by me.

**Comment by blackwings-01** [comment]
Ok updated in spreadsheet and I regenerated the jsons and pushed to plasticine.

**Comment by raghup17** [comment]
Thanks!
